import { useEffect, useMemo, useState } from 'react';
import { duplicateSalesDocument, listSalesDocuments, setSalesDocumentArchived, type DocumentHistoryQuery, type SalesDocument } from '../api/client';

const amount=(doc:SalesDocument)=>`${Number(doc.grandTotalBaseUnit).toLocaleString('fa-IR')} ریال`;
const status=(doc:SalesDocument)=>doc.lifecycleStatus==='cancelled'?'باطل‌شده':doc.lifecycleStatus==='draft'?'پیش‌نویس':doc.documentType==='invoice'?'تسویه‌شده':doc.settlementStatus==='paid'?'تسویه کامل':doc.settlementStatus==='partial'?'پرداخت ناقص':'در انتظار پرداخت';

export function DocumentsPage({preview=false,onOpen}:{preview?:boolean;onOpen:(doc:SalesDocument)=>void}){
  const [documents,setDocuments]=useState<SalesDocument[]>([]);const [loading,setLoading]=useState(!preview);const [error,setError]=useState('');const [query,setQuery]=useState('');const [type,setType]=useState<DocumentHistoryQuery['documentType']>('');const [statusFilter,setStatusFilter]=useState('');const [archived,setArchived]=useState(false);const [cursor,setCursor]=useState<string|null>(null);const [busy,setBusy]=useState('');
  async function load(nextCursor='',append=false){setLoading(true);setError('');try{const page=await listSalesDocuments({query,documentType:type,archived,cursor:nextCursor,limit:20,...(statusFilter==='partial'||statusFilter==='paid'||statusFilter==='unpaid'?{settlementStatus:statusFilter as SalesDocument['settlementStatus']}:(statusFilter?{lifecycleStatus:statusFilter as SalesDocument['lifecycleStatus']}:{}))});setDocuments(current=>append?[...current,...page.documents]:page.documents);setCursor(page.nextCursor);}catch{setError('فهرست اسناد دریافت نشد. دوباره تلاش کنید.');}finally{setLoading(false);}}
  useEffect(()=>{if(preview){setDocuments([]);return;}const timer=window.setTimeout(()=>{void load();},query?250:0);return()=>window.clearTimeout(timer);},[preview,query,type,statusFilter,archived]);
  const groups=useMemo(()=>{const map=new Map<string,{name:string;phone?:string;documents:SalesDocument[]}>();for(const document of documents){const group=map.get(document.customerId)??{name:document.customerName,phone:document.customerPhone,documents:[]};group.documents.push(document);map.set(document.customerId,group);}return [...map.entries()];},[documents]);
  async function duplicate(document:SalesDocument){setBusy(document.id);try{const copy=await duplicateSalesDocument(document.id);onOpen(copy);}catch{setError('ساخت نسخه جدید انجام نشد.');}finally{setBusy('');}}
  async function archive(document:SalesDocument){setBusy(document.id);try{await setSalesDocumentArchived(document.id,!archived);setDocuments(current=>current.filter(row=>row.id!==document.id));}catch{setError('تغییر وضعیت بایگانی انجام نشد.');}finally{setBusy('');}}
  return <div className="page documents-page"><header className="page-header"><span>تاریخچه فروش</span><h1>اسناد مشتریان</h1><p>فاکتورها و پیش‌فاکتورها بر اساس مشتری کنار هم قرار گرفته‌اند.</p></header>
    <section className="history-tools" aria-label="جست‌وجو و فیلتر اسناد"><label><span>جست‌وجو</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="نام، تلفن، شماره سند یا شرح کالا"/></label><div><select aria-label="نوع سند" value={type} onChange={event=>setType(event.target.value as DocumentHistoryQuery['documentType'])}><option value="">همه سندها</option><option value="proforma">پیش‌فاکتور</option><option value="invoice">فاکتور</option></select><select aria-label="وضعیت سند" value={statusFilter} onChange={event=>setStatusFilter(event.target.value)}><option value="">همه وضعیت‌ها</option><option value="draft">پیش‌نویس</option><option value="issued">صادرشده</option><option value="partial">پرداخت ناقص</option><option value="paid">تسویه کامل</option><option value="cancelled">باطل‌شده</option></select><button type="button" className={archived?'active':''} aria-pressed={archived} onClick={()=>setArchived(value=>!value)}>{archived?'اسناد فعال':'بایگانی'}</button></div></section>
    {error&&<section className="history-feedback" role="alert">{error}<button type="button" onClick={()=>void load()}>تلاش دوباره</button></section>}
    {loading&&documents.length===0?<section className="empty-card" role="status"><p>در حال دریافت اسناد…</p></section>:groups.length===0?<section className="empty-card"><div className="empty-visual" aria-hidden="true"><span/><span/><span/></div><div><h2>{archived?'بایگانی خالی است':'سندی پیدا نشد'}</h2><p>عبارت جست‌وجو یا فیلترها را تغییر دهید.</p></div></section>:<section className="customer-history" aria-label="اسناد ثبت‌شده">{groups.map(([customerId,group])=><details key={customerId} open={groups.length===1}><summary><span><strong>{group.name}</strong><small>{group.phone||'بدون شماره تماس'}</small></span><b>{group.documents.length.toLocaleString('fa-IR')} سند</b></summary><div className="documents-list">{group.documents.map(doc=><article className="document-row history-row" key={doc.id}><button type="button" className="document-open" onClick={()=>onOpen(doc)}><span className={`document-kind ${doc.documentType}`}>{doc.documentType==='proforma'?'پیش‌فاکتور':'فاکتور'}</span><span className="document-main"><strong><bdi dir="ltr">{doc.documentNumber??'پیش‌نویس'}</bdi></strong><small>{status(doc)}{doc.sourceDocumentId?' · تبدیل‌شده از پیش‌فاکتور':''}</small></span><span className="document-total"><bdi>{amount(doc)}</bdi><small>{doc.documentType==='proforma'&&doc.settlementStatus==='partial'?`مانده ${Number(doc.remainingAmountBaseUnit).toLocaleString('fa-IR')}`:'مشاهده'}</small></span></button><div className="history-actions"><button type="button" onClick={()=>void duplicate(doc)} disabled={busy===doc.id}>کپی برای سند جدید</button><button type="button" onClick={()=>void archive(doc)} disabled={busy===doc.id}>{archived?'بازگردانی':'بایگانی'}</button></div></article>)}</div></details>)}</section>}
    {cursor&&<button type="button" className="secondary-button history-more" disabled={loading} onClick={()=>void load(cursor,true)}>{loading?'در حال دریافت…':'نمایش اسناد بیشتر'}</button>}
  </div>;
}
