import{useEffect,useMemo,useState}from'react';
import{addProformaPayment,createSalesDraft,finalizeSalesDocument,findCustomers,getBusinessSettings,getSalesDocument,issueFinalInvoice,saveCustomer,updateCustomer,type CustomerProfile,type DocumentType,type SalesDocument}from'../api/client';
type Row={id:string;title:string;quantity:string;price:string;discount:string};
const digits=(v:string)=>v.replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c))).replace(/\D/g,'');
const money=(v:string|number|bigint)=>BigInt(v||0).toLocaleString('fa-IR');
const empty=():Row=>({id:crypto.randomUUID(),title:'',quantity:'1',price:'',discount:''});
const shipping=[['','انتخاب نشده'],['pickup','تحویل حضوری'],['snapp_box','پیک اسنپ‌باکس'],['snapp_car','ماشین اسنپ'],['snapp_van','وانت اسنپ'],['post','پست'],['tipax','تیپاکس']];
export function SalesDocumentPage({type,documentId=null,preview=false,onBack}:{type:DocumentType;documentId?:string|null;preview?:boolean;onBack:()=>void}){
 const[customerId,setCustomerId]=useState<string>();const[name,setName]=useState('');const[phone,setPhone]=useState('');const[address,setAddress]=useState('');const[official,setOfficial]=useState(false);const[nationalId,setNationalId]=useState('');const[ship,setShip]=useState('');const[validity,setValidity]=useState('7');const[notes,setNotes]=useState('');const[rows,setRows]=useState<Row[]>([empty()]);const[taxRate,setTaxRate]=useState(1000);const[matches,setMatches]=useState<CustomerProfile[]>([]);const[doc,setDoc]=useState<SalesDocument|null>(null);const[payment,setPayment]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[showPreview,setShowPreview]=useState(false);
 useEffect(()=>{if(preview)return;void getBusinessSettings().then(x=>setTaxRate(x.settings.financial.taxRateBasisPoints||1000)).catch(()=>{});if(documentId)void getSalesDocument(documentId).then(setDoc).catch(()=>setError('سند پیدا نشد.'));},[documentId,preview]);
 useEffect(()=>{if(preview||customerId||digits(phone).length<11){setMatches([]);return;}const timer=setTimeout(()=>void findCustomers(phone).then(setMatches).catch(()=>setMatches([])),350);return()=>clearTimeout(timer);},[phone,customerId,preview]);
 const totals=useMemo(()=>rows.reduce((a,r)=>{const gross=BigInt(digits(r.quantity)||0)*BigInt(digits(r.price)||0),discount=BigInt(digits(r.discount)||0),net=gross>discount?gross-discount:0n,tax=official?(net*BigInt(taxRate)+5000n)/10000n:0n;return{gross:a.gross+gross,discount:a.discount+discount,tax:a.tax+tax,total:a.total+net+tax};},{gross:0n,discount:0n,tax:0n,total:0n}),[rows,official,taxRate]);
 const customerPayload={displayName:name.trim(),phone:phone.trim(),address:address.trim(),isOfficial:official,nationalId:official?digits(nationalId):''};
 function choose(c:CustomerProfile){setCustomerId(c.id);setName(c.displayName);setPhone(c.phone);setAddress(c.address);setOfficial(c.isOfficial);setNationalId(c.nationalId);setMatches([]);}
 async function keepCustomer(){setBusy(true);setError('');try{const saved=customerId?await updateCustomer(customerId,customerPayload):await saveCustomer(customerPayload);choose(saved);}catch(e){setError(e instanceof Error?e.message:'ذخیره مشتری انجام نشد.');}finally{setBusy(false);}}
 function change(id:string,key:keyof Row,value:string){setRows(rs=>rs.map(r=>r.id===id?{...r,[key]:value}:r));}
 function move(index:number,dir:number){const next=[...rows],to=index+dir;if(to<0||to>=next.length)return;[next[index],next[to]]=[next[to],next[index]];setRows(next);}
 function valid(){if(!name.trim()||digits(phone).length!==11){setError('نام مشتری و شماره همراه معتبر الزامی است.');return false;}if(official&&digits(nationalId).length<10){setError('برای سند رسمی، شناسه ملی الزامی است.');return false;}if(rows.some(r=>!r.title.trim()||!digits(r.price)||Number(digits(r.quantity))<1)){setError('شرح، تعداد و مبلغ همه اقلام را کامل کنید.');return false;}return true;}
 async function create(){if(!valid())return;setBusy(true);setError('');try{const next=preview?fake():await createSalesDraft({documentType:type,customer:{id:customerId,displayName:name.trim(),phone:phone.trim(),nationalId:official?digits(nationalId):undefined},isOfficial:official,address:address.trim(),shippingMethod:ship,validityDays:type==='proforma'&&validity?Number(digits(validity)):null,notes:notes.trim(),items:rows.map(r=>({title:r.title.trim(),quantityMilli:String(Number(digits(r.quantity))*1000),unitPriceBaseUnit:digits(r.price),discountBaseUnit:digits(r.discount)||'0'}))});setDoc(next);}catch(e){setError(e instanceof Error?e.message:'ذخیره پیش‌نویس انجام نشد.');}finally{setBusy(false);}}
 function fake():SalesDocument{return{id:'preview',customerId:customerId||'preview',customerName:name,customerPhone:phone,documentType:type,lifecycleStatus:'draft',settlementStatus:'unpaid',documentNumber:null,sourceDocumentId:null,isOfficial:official,nationalId,customerAddress:address,shippingMethod:ship,validityDays:Number(validity)||null,notes,issueDate:null,validUntil:null,taxRateBasisPoints:official?taxRate:0,taxTotalBaseUnit:String(totals.tax),currencyUnit:'rial',subtotalBaseUnit:String(totals.gross),discountBaseUnit:String(totals.discount),surchargeBaseUnit:'0',grandTotalBaseUnit:String(totals.total),paidAmountBaseUnit:'0',remainingAmountBaseUnit:String(totals.total),version:1,items:rows.map((r,i)=>({title:r.title,description:'',quantityMilli:Number(r.quantity)*1000,unitPriceBaseUnit:digits(r.price),discountBaseUnit:digits(r.discount)||'0',taxBaseUnit:'0',lineTotalBaseUnit:'0',position:i+1})),payments:type==='proforma'?[]:undefined,canIssueFinalInvoice:false};}
 async function finalize(){if(!doc)return;setBusy(true);try{setDoc(preview?{...doc,lifecycleStatus:'issued',documentNumber:type==='proforma'?'PF-00001':'INV-00001',issueDate:'۱۴۰۵/۰۶/۱۹',settlementStatus:type==='invoice'?'paid':'unpaid'}:await finalizeSalesDocument(doc.id,type==='invoice'));}catch(e){setError(e instanceof Error?e.message:'صدور انجام نشد.');}finally{setBusy(false);}}
 async function pay(){if(!doc||!digits(payment))return;setBusy(true);try{if(preview){const next=BigInt(doc.paidAmountBaseUnit)+BigInt(digits(payment)),total=BigInt(doc.grandTotalBaseUnit);if(next>total)throw new Error('مبلغ بیشتر از مانده است.');setDoc({...doc,paidAmountBaseUnit:String(next),remainingAmountBaseUnit:String(total-next),settlementStatus:next===total?'paid':'partial',canIssueFinalInvoice:next===total});}else setDoc(await addProformaPayment(doc.id,digits(payment),crypto.randomUUID()));setPayment('');}catch(e){setError(e instanceof Error?e.message:'ثبت پرداخت انجام نشد.');}finally{setBusy(false);}}
 async function share(){if(!doc||doc.lifecycleStatus!=='issued')return;const text=`${doc.documentType==='proforma'?'پیش‌فاکتور':'فاکتور'} ${doc.documentNumber}\n${doc.customerName}\n${money(doc.grandTotalBaseUnit)} ریال`;if(navigator.share)await navigator.share({title:'سند میرا',text});else await navigator.clipboard.writeText(text);}
 if(doc)return <div className="page sales-page"><button className="sales-back" onClick={onBack}>بازگشت</button><DocumentSummary doc={doc} payment={payment} setPayment={setPayment} busy={busy} onFinalize={finalize} onPay={pay} onConvert={async()=>setDoc(preview?{...doc,documentType:'invoice',sourceDocumentId:doc.id,documentNumber:'INV-00001'}:await issueFinalInvoice(doc.id))} onShare={share}/>{error&&<p className="sales-message" role="alert">{error}</p>}</div>;
 return <div className="page sales-page builder-page"><button className="sales-back" onClick={onBack}>بازگشت</button><header className="sales-heading"><span>فرم یک‌صفحه‌ای</span><h1>ساخت سند جدید</h1><p>همه اطلاعات را در همین صفحه وارد و در پایین بازبینی کنید.</p></header>
 <section className="sales-card builder-section"><div className="doc-type-switch"><button className={type==='proforma'?'active':''}>پیش‌فاکتور</button><button className={type==='invoice'?'active':''}>فاکتور فروش</button></div><label>نام مشتری یا شرکت *<input aria-label="نام مشتری یا شرکت" value={name} onChange={e=>setName(e.target.value)}/></label><label>شماره تماس *<input aria-label="شماره تماس" dir="ltr" inputMode="tel" value={phone} onChange={e=>{setPhone(e.target.value);setCustomerId(undefined);}} placeholder="0912…"/></label>{matches.length>0&&<div className="customer-matches">{matches.map(c=><button key={c.id} onClick={()=>choose(c)}><strong>{c.displayName}</strong><span dir="ltr">{c.phone}</span></button>)}</div>}<div className="customer-actions"><button type="button" className="secondary-button" disabled={busy} onClick={keepCustomer}>{customerId?'به‌روزرسانی اطلاعات مشتری':'+ افزودن به مشتریان'}</button>{customerId&&<span>مشتری ذخیره‌شده</span>}</div><label className="official-toggle"><span><strong>سند رسمی</strong><small>در سند رسمی مالیات اعمال می‌شود.</small></span><input type="checkbox" checked={official} onChange={e=>setOfficial(e.target.checked)}/></label>{official&&<label>شناسه ملی *<input aria-label="شناسه ملی" dir="ltr" inputMode="numeric" value={nationalId} onChange={e=>setNationalId(e.target.value)}/></label>}
 <details><summary>آدرس (اختیاری)</summary><textarea value={address} onChange={e=>setAddress(e.target.value)} rows={3}/></details><details><summary>شیوه ارسال (اختیاری)</summary><select value={ship} onChange={e=>setShip(e.target.value)}>{shipping.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>{ship&&ship!=='pickup'&&<small>کرایه در مقصد</small>}</details>{type==='proforma'&&<details><summary>مدت اعتبار (اختیاری)</summary><input aria-label="مدت اعتبار" type="number" min="0" max="365" value={validity} onChange={e=>setValidity(e.target.value)}/></details>}<details><summary>توضیحات (اختیاری)</summary><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3}/></details></section>
 <section className="sales-card builder-section"><div className="builder-title"><h2>اقلام سند</h2><span>{rows.length.toLocaleString('fa-IR')} قلم</span></div>{rows.map((r,i)=><article className="item-editor" key={r.id}><div className="item-toolbar"><b>ردیف {(i+1).toLocaleString('fa-IR')}</b><span><button aria-label="بالا" onClick={()=>move(i,-1)}>↑</button><button aria-label="پایین" onClick={()=>move(i,1)}>↓</button>{rows.length>1&&<button aria-label="حذف قلم" onClick={()=>setRows(x=>x.filter(a=>a.id!==r.id))}>حذف</button>}</span></div><label>شرح کالا یا خدمت *<input value={r.title} onChange={e=>change(r.id,'title',e.target.value)}/></label><div className="item-numbers"><label>تعداد *<input inputMode="numeric" value={r.quantity} onChange={e=>change(r.id,'quantity',e.target.value)}/></label><label>مبلغ واحد (ریال) *<input inputMode="numeric" value={r.price} onChange={e=>change(r.id,'price',e.target.value)}/></label></div><label>تخفیف ردیف (اختیاری)<input inputMode="numeric" value={r.discount} onChange={e=>change(r.id,'discount',e.target.value)}/></label></article>)}<button className="add-item" onClick={()=>setRows(x=>[...x,empty()])}>+ افزودن قلم جدید</button><div className="builder-totals"><span>جمع اقلام <b>{money(totals.gross)} ریال</b></span>{totals.discount>0&&<span>تخفیف ردیف‌ها <b>{money(totals.discount)} ریال</b></span>}<span>مالیات بر ارزش افزوده {official?taxRate/100:0}٪ <b>{money(totals.tax)} ریال</b></span><strong>مبلغ نهایی <b>{money(totals.total)} ریال</b></strong></div></section>
 <section className="sales-card builder-section preview-section"><div className="auto-meta"><span>شماره سند: خودکار</span><span>تاریخ صدور: خودکار</span>{type==='proforma'&&validity&&<span>اعتبار: {Number(validity).toLocaleString('fa-IR')} روز</span>}</div><h2>پیش‌نمایش سند</h2><div className="document-mini"><header><b>{type==='proforma'?'پیش‌فاکتور':'فاکتور فروش'}</b><span>{name||'نام مشتری'}</span></header><table><thead><tr><th>شرح</th><th>تعداد</th><th>مبلغ</th>{official&&<th>مالیات {taxRate/100}٪</th>}</tr></thead><tbody>{rows.filter(r=>r.title).map(r=><tr key={r.id}><td>{r.title}</td><td>{r.quantity}</td><td>{money(digits(r.price)||0)}</td>{official&&<td>—</td>}</tr>)}</tbody></table><footer>جمع نهایی: {money(totals.total)} ریال</footer></div><p className="bank-note">تمام حساب‌های واریزی تعریف‌شده در تنظیمات، خودکار روی پیش‌فاکتور صادرشده نمایش داده می‌شوند.</p><button className="secondary-button full-preview" onClick={()=>setShowPreview(true)}>پیش‌نمایش کامل</button>{showPreview&&<div className="preview-dialog" role="dialog"><button onClick={()=>setShowPreview(false)}>بستن</button><div className="document-mini enlarged">پیش‌نمایش A4 افقی · {rows.length.toLocaleString('fa-IR')} قلم · {money(totals.total)} ریال</div></div>}<button className="primary-button sales-primary" disabled={busy} onClick={create}>ذخیره و ادامه برای صدور</button><button className="share-disabled" disabled>اشتراک‌گذاری <small>پس از صدور فعال می‌شود</small></button></section>{error&&<p className="sales-message" role="alert">{error}</p>}</div>;
}
function DocumentSummary({doc,payment,setPayment,busy,onFinalize,onPay,onConvert,onShare}:{doc:SalesDocument;payment:string;setPayment:(v:string)=>void;busy:boolean;onFinalize:()=>void;onPay:()=>void;onConvert:()=>void;onShare:()=>void}){return <section className="sales-card document-summary"><div className="document-badge">{doc.documentType==='proforma'?'پیش‌فاکتور':'فاکتور فروش'} · {doc.lifecycleStatus==='draft'?'پیش‌نویس':'صادرشده'}</div><h2>{doc.customerName}</h2><div className="money-row"><span>مبلغ کل</span><strong>{money(doc.grandTotalBaseUnit)} ریال</strong></div>{doc.documentType==='proforma'&&doc.lifecycleStatus==='issued'&&<div className="balance-grid"><div><span>پرداخت‌شده</span><strong>{money(doc.paidAmountBaseUnit)}</strong></div><div><span>مانده</span><strong>{money(doc.remainingAmountBaseUnit)}</strong></div></div>}{doc.lifecycleStatus==='draft'?<button className="primary-button sales-primary" disabled={busy} onClick={onFinalize}>{doc.documentType==='invoice'?'تأیید پرداخت کامل و صدور فاکتور':'صدور پیش‌فاکتور'}</button>:<>{doc.documentType==='proforma'&&!doc.canIssueFinalInvoice&&<div className="payment-box"><label>ثبت پرداخت<input aria-label="مبلغ پرداخت" inputMode="numeric" value={payment} onChange={e=>setPayment(e.target.value)}/></label><button className="primary-button" onClick={onPay}>ثبت پرداخت</button></div>}{doc.documentType==='proforma'&&doc.canIssueFinalInvoice&&<button className="primary-button" onClick={onConvert}>صدور فاکتور نهایی</button>}{doc.documentType==='invoice'&&<div className="settled-note">پرداخت کامل شده · جزئیات اقساط در این فاکتور نمایش داده نمی‌شود.</div>}<button className="secondary-button" onClick={onShare}>اشتراک‌گذاری</button></>}</section>}
