import { useEffect, useState } from 'react';
import { addProformaPayment, createSalesDraft, finalizeSalesDocument, getSalesDocument, issueFinalInvoice, type DocumentType, type SalesDocument } from '../api/client';

const key=(type:DocumentType)=>`mira:g04:draft:${type}`;
const number=(value:string)=>value.replace(/[۰-۹]/g,c=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(c))).replace(/\D/g,'');
const money=(value:string|number)=>Number(value).toLocaleString('fa-IR');

export function SalesDocumentPage({type,documentId=null,preview=false,onBack}:{type:DocumentType;documentId?:string|null;preview?:boolean;onBack:()=>void}){
  const [customer,setCustomer]=useState(''); const [title,setTitle]=useState(''); const [amount,setAmount]=useState('');
  const [doc,setDoc]=useState<SalesDocument|null>(null); const [payment,setPayment]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const label=type==='proforma'?'پیش‌فاکتور':'فاکتور فروش';
  useEffect(()=>{if(preview)return;const id=documentId??localStorage.getItem(key(type));if(id)void getSalesDocument(id).then(setDoc).catch(()=>{if(!documentId)localStorage.removeItem(key(type));setError('سند پیدا نشد یا اجازه دسترسی ندارید.');});},[documentId,preview,type]);
  function fake():SalesDocument{const total=number(amount);return{id:'preview-draft',customerId:'preview-customer',customerName:customer,documentType:type,lifecycleStatus:'draft',settlementStatus:'unpaid',documentNumber:null,sourceDocumentId:null,currencyUnit:'rial',subtotalBaseUnit:total,discountBaseUnit:'0',surchargeBaseUnit:'0',grandTotalBaseUnit:total,paidAmountBaseUnit:'0',remainingAmountBaseUnit:total,version:1,items:[{title,description:'',quantityMilli:'1000',unitPriceBaseUnit:total,lineTotalBaseUnit:total,position:1}],payments:type==='proforma'?[]:undefined,canIssueFinalInvoice:false};}
  async function run(action:()=>Promise<SalesDocument>){setBusy(true);setError('');try{setDoc(await action());}catch(e){setError(e instanceof Error?e.message:'عملیات انجام نشد');}finally{setBusy(false);}}
  function create(){const total=number(amount);if(!customer.trim()||!title.trim()||!total||total==='0'){setError('نام مشتری، شرح و مبلغ را کامل کنید.');return;}void run(async()=>{const next=preview?fake():await createSalesDraft({documentType:type,customer:{displayName:customer.trim()},items:[{title:title.trim(),quantityMilli:'1000',unitPriceBaseUnit:total}]});if(!preview)localStorage.setItem(key(type),next.id);return next;});}
  function finalize(){if(!doc)return;void run(async()=>{const next=preview?{...doc,lifecycleStatus:'issued' as const,settlementStatus:type==='invoice'?'paid' as const:'unpaid' as const,paidAmountBaseUnit:type==='invoice'?doc.grandTotalBaseUnit:'0',remainingAmountBaseUnit:type==='invoice'?'0':doc.grandTotalBaseUnit,documentNumber:type==='invoice'?'INV-00001':'PF-00001'}:await finalizeSalesDocument(doc.id,type==='invoice');if(!preview)localStorage.removeItem(key(type));return next;});}
  function pay(){if(!doc)return;const value=number(payment);if(!value||value==='0')return;void run(async()=>{if(!preview)return addProformaPayment(doc.id,value,crypto.randomUUID());const paid=Number(doc.paidAmountBaseUnit)+Number(value),total=Number(doc.grandTotalBaseUnit);if(paid>total)throw new Error('مبلغ پرداخت بیشتر از مانده است.');setPayment('');return{...doc,paidAmountBaseUnit:String(paid),remainingAmountBaseUnit:String(total-paid),settlementStatus:paid===total?'paid':'partial',canIssueFinalInvoice:paid===total,payments:[...(doc.payments??[]),{id:String(paid),amount_base_unit:value,paid_at:'اکنون',method:'manual',reference_text:'',note:'',status:'confirmed'}]};});}
  function convert(){if(!doc)return;void run(async()=>preview?{...doc,id:'preview-invoice',documentType:'invoice',sourceDocumentId:doc.id,documentNumber:'INV-00001',payments:undefined}:issueFinalInvoice(doc.id));}
  return <div className="page sales-page"><button className="sales-back" onClick={onBack}>بازگشت</button><header className="sales-heading"><span>{type==='proforma'?'پیشنهاد و دریافت بیعانه':'فروش تسویه‌شده'}</span><h1>{doc?.documentNumber||`ساخت ${label}`}</h1><p>اطلاعات اصلی را وارد کنید؛ تنظیمات پیشرفته از تنظیمات میرا خوانده می‌شود.</p></header>
    {!doc?<section className="sales-card"><label>نام مشتری<input aria-label="نام مشتری" value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="مثلاً شرکت نمونه"/></label><label>شرح کالا یا خدمت<input aria-label="شرح کالا یا خدمت" value={title} onChange={e=>setTitle(e.target.value)} placeholder="شرح سفارش"/></label><label>مبلغ کل (ریال)<input aria-label="مبلغ کل" inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="۱۰۰٬۰۰۰٬۰۰۰"/></label><div className="live-total"><span>جمع سند</span><strong>{money(number(amount)||0)} ریال</strong></div><button className="primary-button sales-primary" disabled={busy} onClick={create}>ذخیره پیش‌نویس</button></section>
    :<section className="sales-card document-summary"><div className="document-badge">{doc.documentType==='proforma'?'پیش‌فاکتور':'فاکتور فروش'} · {doc.lifecycleStatus==='draft'?'پیش‌نویس':'صادرشده'}</div><h2>{doc.items[0]?.title}</h2><div className="money-row"><span>مبلغ کل</span><strong>{money(doc.grandTotalBaseUnit)} {doc.currencyUnit==='toman'?'تومان':'ریال'}</strong></div>{doc.documentType==='proforma'&&<><div className="progress" aria-label="پیشرفت پرداخت"><span style={{width:`${Number(doc.grandTotalBaseUnit)?Number(doc.paidAmountBaseUnit)*100/Number(doc.grandTotalBaseUnit):0}%`}}/></div><div className="balance-grid"><div><span>پرداخت‌شده</span><strong>{money(doc.paidAmountBaseUnit)}</strong></div><div><span>مانده</span><strong>{money(doc.remainingAmountBaseUnit)}</strong></div></div></>}{doc.lifecycleStatus==='draft'?<button className="primary-button sales-primary" disabled={busy} onClick={finalize}>{type==='invoice'?'تأیید پرداخت کامل و صدور فاکتور':'صدور پیش‌فاکتور'}</button>:doc.documentType==='proforma'&&!doc.canIssueFinalInvoice?<div className="payment-box"><label>ثبت پرداخت<input aria-label="مبلغ پرداخت" inputMode="numeric" value={payment} onChange={e=>setPayment(e.target.value)} placeholder="مبلغ بیعانه یا مانده"/></label><button className="primary-button sales-primary" disabled={busy} onClick={pay}>ثبت پرداخت</button></div>:doc.documentType==='proforma'?<button className="primary-button sales-primary" disabled={busy} onClick={convert}>صدور فاکتور نهایی</button>:<div className="settled-note">پرداخت کامل شده · جزئیات اقساط در این فاکتور نمایش داده نمی‌شود.</div>}</section>}{error&&<p className="sales-message" role="alert">{error}</p>}</div>;
}
