import { describe, expect, it } from 'vitest';
import { documentViewModel, paginateDocumentModel } from './DocumentExportActions';
import type { SalesDocument } from '../api/client';

const document:SalesDocument={id:'doc',customerId:'customer',customerName:'خریدار',customerPhone:'09120000000',documentType:'invoice',lifecycleStatus:'issued',settlementStatus:'paid',documentNumber:'INV-1',sourceDocumentId:null,currencyUnit:'rial',subtotalBaseUnit:'1000000',discountBaseUnit:'0',surchargeBaseUnit:'0',grandTotalBaseUnit:'1100000',paidAmountBaseUnit:'1100000',remainingAmountBaseUnit:'0',version:2,isOfficial:true,nationalId:'1234567890',customerAddress:'تهران',taxRateBasisPoints:1000,taxTotalBaseUnit:'100000',items:[{title:'کالا',description:'',quantityMilli:'1000',unitPriceBaseUnit:'1000000',discountBaseUnit:'0',taxBaseUnit:'100000',lineTotalBaseUnit:'1100000',position:1}],canIssueFinalInvoice:false};

describe('G06 immutable export view model',()=>{
  it('keeps Rial totals and official VAT while omitting invoice payment destinations',()=>{const model=documentViewModel(document);expect(model.grandTotalRial).toBe('1100000');expect(model.taxRial).toBe('100000');expect(model.customer.legalId).toBe('1234567890');expect(model.payment).toBeUndefined();expect(model.orientation).toBe('landscape');});
  it('shows snapshotted payment destinations only on proformas',()=>{const model=documentViewModel({...document,documentType:'proforma',settlementStatus:'unpaid',paidAmountBaseUnit:'0',settingsSnapshot:{seller:{businessName:'فروشنده',displayName:'',subtitle:'',sellerName:'',phone:'',telegramUsername:'',address:'',showAddress:false,customContactLine:''},payment:{accounts:[{cardNumber:'1',sheba:'IR1',bankName:'بانک',accountHolder:'نام'}],cardNumber:'',accountNumber:'',sheba:'',bankName:'',accountHolder:'',instructions:''},officialSeller:{companyName:'شرکت',address:'تهران',phone:'021',nationalId:'12345678901'},officialPayment:{accounts:[{cardNumber:'2',sheba:'IROFFICIAL',bankName:'بانک',accountHolder:'شرکت'}],cardNumber:'',accountNumber:'',sheba:'',bankName:'',accountHolder:'',instructions:''},document:{proformaLabel:'',invoiceLabel:'',numberingMode:'auto',proformaPrefix:'PF',invoicePrefix:'INV',numberPadding:5,issueDateMode:'today',validityDays:7,calendar:'jalali',digits:'persian'},presentation:{currencyUnit:'rial',thousandsSeparator:true,decimalPolicy:'none',roundTotal:'none'},items:{rowNumber:true,sku:false,image:false,title:true,description:true,unit:false,quantity:true,unitPrice:true,lineDiscount:true,tax:true,lineTotal:true},financial:{discount:{kind:'none',amountBaseUnit:'0',percentBasisPoints:0},shippingAmountBaseUnit:'0',serviceFeeAmountBaseUnit:'0',taxEnabled:true,taxRateBasisPoints:1000,customAdjustments:[]},text:{sellerNote:'',paymentTerms:'',shippingTerms:'',footer:'',validityNotice:'',thankYou:''},visual:{templateId:'classic-business',accent:'#80622b',invoiceVariant:'light',logoPosition:'start',density:'comfortable',fontSize:'medium'}}});expect(model.payment?.accounts?.[0].sheba).toBe('IROFFICIAL');expect(model.templateId).toBe('classic-business');});
  it('paginates a 100-row document without dropping or duplicating rows',()=>{const base=documentViewModel(document);const items=Array.from({length:100},(_,index)=>({...base.items[0],row:index+1,title:`ردیف ${index+1}`}));const pages=paginateDocumentModel({...base,items});expect(pages).toHaveLength(9);expect(pages.flatMap(page=>page.items)).toHaveLength(100);expect(pages.at(-1)?.items.at(-1)?.row).toBe(100);});
});
