import{getTemplate}from'./registry';import type{InvoiceViewModel,PartyViewModel}from'./types';
const rial=(value?:string)=>value&&BigInt(value).toLocaleString('fa-IR');
function Rows({party}:{party:PartyViewModel}){const rows=[['نام',party.name],['شناسه ملی',party.legalId],['شماره اقتصادی',party.economicId],['شماره ثبت',party.registrationId],['کدپستی',party.postalCode],['تلفن',party.phone],['نشانی',party.address],['ایمیل',party.email],['تلگرام',party.telegram]].filter(([,v])=>v);return <>{rows.map(([k,v])=><div className="tpl-info-row" key={k}><b>{k}</b><span>{v}</span></div>)}</>}
export function InvoiceTemplate({model,compact=false}:{model:InvoiceViewModel;compact?:boolean}){const def=getTemplate(model.templateId);const moneyRows=[['جمع اقلام',model.subtotalRial],['تخفیف',model.discountRial],['مالیات بر ارزش افزوده',model.taxRial],['هزینه حمل',model.shippingRial],['هزینه خدمات',model.serviceFeeRial],...(model.adjustments??[]).map(a=>[a.label,`${a.direction==='discount'?'-':''}${a.amountRial}`])].filter(([,v])=>v&&v!=='0');const notes=[model.sellerNote,model.paymentTerms,model.shippingTerms,model.validityNotice].filter(Boolean);const accounts=model.payment?.accounts??[];const payment=accounts.length>0||Object.entries(model.payment??{}).some(([k,v])=>k!=='accounts'&&Boolean(v));return <article className={`invoice-template tpl-${def.id} ${model.orientation}${compact?' compact-preview':''}`} style={{'--tpl-accent':model.accent||def.accent} as React.CSSProperties} data-template={`${def.id}@${def.version}`} data-orientation={model.orientation}>{model.cancelled&&<div className="document-cancelled-mark">باطل‌شده</div>}
  <header className="tpl-header"><div className="tpl-brand">{model.seller.logoUrl&&<img src={model.seller.logoUrl} alt="لوگوی فروشنده"/>}<div><strong>{model.seller.name}</strong>{model.seller.subtitle&&<small>{model.seller.subtitle}</small>}</div></div><h1>{model.documentType==='proforma'?'پیش‌فاکتور فروش کالا و خدمات':'فاکتور فروش کالا و خدمات'}</h1><div className="tpl-meta"><span>شماره: <bdi dir="ltr">{model.documentNumber}</bdi></span><span>تاریخ: {model.issueDate}</span>{model.validUntil&&<span>اعتبار تا: {model.validUntil}</span>}{model.orderNumber&&<span>سفارش: <bdi dir="ltr">{model.orderNumber}</bdi></span>}</div></header>
  <section className="tpl-parties"><div><h2>مشخصات فروشنده</h2><Rows party={model.seller}/></div><div><h2>مشخصات خریدار</h2><Rows party={model.customer}/></div></section>
  <div className="tpl-table-wrap"><table><thead><tr><th>ردیف</th>{model.items.some(i=>i.sku)&&<th>کد</th>}<th>شرح کالا یا خدمت</th>{model.items.some(i=>i.unit)&&<th>واحد</th>}<th>تعداد</th><th>مبلغ واحد (ریال)</th>{model.items.some(i=>i.discountRial)&&<th>تخفیف (ریال)</th>}{model.items.some(i=>i.taxRial)&&<th>مالیات بر ارزش افزوده {((model.taxRateBasisPoints??0)/100).toLocaleString('fa-IR')}٪ (ریال)</th>}<th>مبلغ کل (ریال)</th></tr></thead><tbody>{model.items.map(item=><tr key={item.row}><td>{item.row.toLocaleString('fa-IR')}</td>{model.items.some(i=>i.sku)&&<td><bdi dir="ltr">{item.sku||'—'}</bdi></td>}<td><strong>{item.title}</strong>{item.description&&<small>{item.description}</small>}</td>{model.items.some(i=>i.unit)&&<td>{item.unit||'—'}</td>}<td>{item.quantity}</td><td>{rial(item.unitPriceRial)}</td>{model.items.some(i=>i.discountRial)&&<td>{rial(item.discountRial)||'—'}</td>}{model.items.some(i=>i.taxRial)&&<td>{rial(item.taxRial)||'—'}</td>}<td>{rial(item.totalRial)}</td></tr>)}</tbody></table></div>
  <section className="tpl-lower"><div className="tpl-totals">{moneyRows.map(([k,v])=><div key={k}><span>{k} (ریال)</span><b>{rial(v)}</b></div>)}<div className="grand"><span>جمع نهایی (ریال)</span><b>{rial(model.grandTotalRial)}</b></div></div>{payment&&<div className="tpl-payment"><h2>اطلاعات پرداخت</h2>{accounts.map((a,i)=><div key={i}>{a.bankName&&<p>بانک: {a.bankName}</p>}{a.accountHolder&&<p>صاحب حساب: {a.accountHolder}</p>}{a.cardNumber&&<p>کارت: <bdi dir="ltr">{a.cardNumber}</bdi></p>}{a.sheba&&<p>شبا: <bdi dir="ltr">{a.sheba}</bdi></p>}</div>)}{accounts.length===0&&<>{model.payment?.bankName&&<p>بانک: {model.payment.bankName}</p>}{model.payment?.accountHolder&&<p>صاحب حساب: {model.payment.accountHolder}</p>}{model.payment?.cardNumber&&<p>کارت: <bdi dir="ltr">{model.payment.cardNumber}</bdi></p>}{model.payment?.accountNumber&&<p>حساب: <bdi dir="ltr">{model.payment.accountNumber}</bdi></p>}{model.payment?.sheba&&<p>شبا: <bdi dir="ltr">{model.payment.sheba}</bdi></p>}</>}{model.payment?.instructions&&<p>{model.payment.instructions}</p>}</div>}</section>
  {notes.length>0&&<section className="tpl-notes"><h2>شرایط و توضیحات</h2>{notes.map((n,i)=><p key={i}>{n}</p>)}</section>}
  {model.signature&&<section className="tpl-signatures"><div>{model.signature.sellerLabel||'مهر و امضای فروشنده'}</div><div>{model.signature.customerLabel||'مهر و امضای خریدار'}</div></section>}
  {(model.thankYou||model.footer)&&<footer>{model.thankYou&&<strong>{model.thankYou}</strong>}{model.footer&&<span>{model.footer}</span>}</footer>}
 </article>}
