import { useCallback, useEffect, useMemo, useState } from 'react';
import { authenticateWithTelegram, getPilotStatus, submitPilotFeedback, type PilotFeedbackStatus, type PilotMissingCategory, type SessionUser } from './api/client';
import { SettingsPage } from './settings/SettingsPage';
import { SalesDocumentPage } from './sales/SalesDocumentPage';
import { DocumentsPage } from './sales/DocumentsPage';
import { TemplatesPage } from './templates/TemplatesPage';
import type { DocumentType, SalesDocument } from './api/client';
import { applyRuntimeCssVariables, TelegramAdapter, type TelegramRuntimeSnapshot } from './telegram/adapter';
import { shouldReduceMotion } from './motion';

export type AppTab = 'home' | 'invoices' | 'settings' | 'templates';
export type ShellState = 'loading' | 'ready' | 'offline' | 'error';
export interface RecentInvoice { id: string; customer: string; amount: string; date: string; status: 'draft' | 'final' }
export interface HomeData { recentInvoices: RecentInvoice[]; businessName?: string; settingsComplete: boolean }
const emptyHome: HomeData = { recentInvoices: [], settingsComplete: false };

function Icon({ name }: { name: 'home' | 'invoice' | 'settings' | 'templates' | 'plus' | 'spark' | 'store' | 'arrow' | 'retry' }) {
  const paths = {
    home: <><path d="M3 10.8 12 3l9 7.8"/><path d="M5.5 9.5v10h13v-10M9.5 19.5v-6h5v6"/></>,
    invoice: <><path d="M6 3.5h12v17l-3-2-3 2-3-2-3 2z"/><path d="M9 8h6M9 12h6"/></>,
    settings: <><circle cx="12" cy="12" r="3"/><path d="M19 15a2 2 0 0 0 .4 2l-2.5 2.5a2 2 0 0 0-2-.4 2 2 0 0 0-1.3 1.6h-3.4A2 2 0 0 0 9 19a2 2 0 0 0-2 .4L4.6 17a2 2 0 0 0 .4-2 2 2 0 0 0-1.7-1.3v-3.4A2 2 0 0 0 5 9a2 2 0 0 0-.4-2L7 4.6A2 2 0 0 0 9 5a2 2 0 0 0 1.3-1.7h3.4A2 2 0 0 0 15 5a2 2#uÒÚ$z{-®éÜj×F6WBæÖ÷F–öâÒ6†÷VÆE&VGV6TÖ÷F–öâ‚’òw&VGV6VBr¢vgVÆÂs²FVÆVw&Òç&VG’‚“²FVÆVw&ÒæW‡æB‚“²6öç7BWFFRÒ‚’Óâ²6öç7BæW‡BÒFVÆVw&Òç6æ6†÷B‚“²Ç•'VçF–ÖT775f&–&ÆW2†æW‡B“²6WE'VçF–ÖR†æW‡B“²Ó²WFFR‚“²6öç7BVç7V'67&–&RÒFVÆVw&Òæöå'VçF–ÖT6†ævR‡WFFR“²&WGW&âVç7V'67&–&S²ÒÂ·FVÆVw&ÕÒ“°¢W6TVffV7B‚‚’Óâ²ÆWB6æ6VÆÆVBÒfÇ6S²7–æ2gVæ7F–öâ&ö÷G7G&‚’²–b‡&Wf–Wr’&WGW&ã²6WE7FFR‚vÆöF–ærr“²6WDW'&÷"‚rr“²–b‚æf–vF÷"æöäÆ–æR’²6WE7FFR‚vöffÆ–æRr“²&WGW&ã²ÒG'’²6öç7B–æ—DFFÒFVÆVw&ÒævWD–æ—DFF‚“²–b‚–æ—DFF’F‡&÷ræWrW'&÷"‚}Š}¸Í˜b‹]˜ŠÝ˜r‹ŠrŠ}‹"Šýª˜]˜}™B˜]˜m˜¸Â‹ŠŠ}Š¢Š­˜Mªý‹Š}˜RŠŠ}‹"ª˜m¸ÍŠòâr“²6öç7BWF†VçF–6FVBÒv—BWF†VçF–6FUv—F…FVÆVw&Ò†–æ—DFF“²–b†6æ6VÆÆVB’&WGW&ã²6WE6W76–öâ†WF†VçF–6FVB“²6WE7FFR‚w&VG’r“²FVÆVw&Òæ†F–2‚w7V66W72r“²fö–BvWE–Æ÷E7FGW2‚’çF†Vâ‡fÇVSÓç¶–b‚6æ6VÆÆVB—6WE–Æ÷DfVVF&6²‡fÇVRæfVVF&6²“·Ò’æ6F6‚‚‚“ÓçVæFVf–æVB“²Ò6F6‚‡&V6öâ’²–b†6æ6VÆÆVB’&WGW&ã²6WDW'&÷"‡&V6öâ–ç7Fæ6VöbW'&÷"ò&V6öâæÖW76vR¢}Ší‹}Š}¸Â˜mŠ}‹M˜mŠ}ŠíŠ­˜rŠý‹Š‹˜-‹Š}‹¸Â˜m‹M‹=Š¢Š}˜]˜br“²6WE7FFR‚vW'&÷"r“²ÒÒfö–B&ö÷G7G&‚“²&WGW&â‚’Óâ²6æ6VÆÆVBÒG'VS²Ó²ÒÂ¶GFV×BÂ&Wf–WrÂFVÆVw&ÕÒ“°¢W6TVffV7B‚‚’Óâ²6öç7BöffÆ–æRÒ‚’Óâ6WE7FFR‚vöffÆ–æRr“²6öç7BöæÆ–æRÒ‚’Óâ6WDGFV×B‡fÇVRÓâfÇVR²“²v–æF÷ræFDWfVçDÆ—7FVæW"‚vöffÆ–æRrÂöffÆ–æR“²v–æF÷ræFDWfVçDÆ—7FVæW"‚vöæÆ–æRrÂöæÆ–æR“²&WGW&â‚’Óâ²v–æF÷rç&VÖ÷fTWfVçDÆ—7FVæW"‚vöffÆ–æRrÂöffÆ–æR“²v–æF÷rç&VÖ÷fTWfVçDÆ—7FVæW"‚vöæÆ–æRrÂöæÆ–æR“²Ó²ÒÂµÒ“°¢–b‡&Wf–Wr’&WGW&âÄ6†VÆÂFVÆVw&Ó×·FVÆVw&×Ò&Wf–Wr'VçF–ÖS×·²ââç'VçF–ÖRÂ6öÆ÷%66†VÖS¢æWrU$Å6V&6…&×2‡v–æF÷ræÆö6F–öâç6V&6‚’ævWB‚wF†VÖRr’ÓÓÒvF&²ròvF&²r¢vÆ–v‡Br×Òóã°¢–b‡7FFRÓÒw&VG’rÇÂ6W76–öâ’&WGW&âÆÖ–â6Æ74æÖSÒ&×6†VÆÂ7FFR×6†VÆÂ"FF×F†VÖS×·'VçF–ÖRæ6öÆ÷%66†VÖWÓãÅ7FGW5f–Wr7FFS×·7FFRÓÓÒw&VG’ròvW'&÷"r¢7FFWÒÖW76vS×¶W'&÷"ÇÂVæFVf–æVGÒöå&WG'“×·7FFRÓÓÒvÆöF–ærròVæFVf–æVB¢‚’Óâ6WDGFV×B‡fÇVRÓâfÇVR²—ÒóãÂöÖ–ãã°¢&WGW&âÄ6†VÆÂFVÆVw&Ó×·FVÆVw&×Ò'VçF–ÖS×·'VçF–ÖWÒ'W6–æW74–C×·6W76–öâæ'W6–æW74–GÒ–Æ÷DfVVF&6³×·–Æ÷DfVVF&6·ÒöäfVVF&6µ7V&Ö—GFVC×²‚“Óç6WE–Æ÷DfVVF&6²†7W'&VçCÓæ7W'&VçC÷²ââæ7W'&VçBÆVÆ–v–&ÆS¦fÇ6RÇ7V&Ö—GFVC§G'VWÓ¦7W'&VçB—Òóã°§Ð